version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
